# Generated by Django 5.2.16 on 2026-07-11 07:06

# pyrefly: ignore [missing-import]
import django.core.validators
# pyrefly: ignore [missing-import]
import django.db.models.deletion
# pyrefly: ignore [missing-import]
from django.conf import settings
# pyrefly: ignore [missing-import]
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Workout title or theme', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the workout')),
                ('session_type', models.CharField(choices=[('1on1', 'One-on-One'), ('group', 'Group')], default='1on1', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scheduled_datetime', models.DateTimeField(help_text='When the workout is scheduled')),
                ('duration_minutes', models.IntegerField(default=60, help_text='Duration in minutes (15-480)', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)])),
                ('location', models.CharField(help_text='Gym name, facility, or meeting location', max_length=200)),
                ('intensity', models.CharField(blank=True, choices=[('low', 'Low Intensity'), ('moderate', 'Moderate Intensity'), ('high', 'High Intensity')], default='moderate', max_length=20)),
                ('focus_areas', models.JSONField(blank=True, default=list, help_text="List of focus areas (e.g., ['strength', 'cardio'])")),
                ('equipment_needed', models.JSONField(blank=True, default=list, help_text='List of equipment participants should bring')),
                ('max_participants', models.IntegerField(default=2, help_text='Maximum number of participants (for group sessions)', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(20)])),
                ('current_participants', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Private notes for participants')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(blank=True, help_text='The invited participant (null for open sessions)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workout Session',
                'verbose_name_plural': 'Workout Sessions',
                'ordering': ['scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='SessionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Message to session creator')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_requests', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='workouts.workoutsession')),
            ],
            options={
                'verbose_name': 'Session Request',
                'verbose_name_plural': 'Session Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('attended', 'Attended'), ('no_show', 'No Show')], default='invited', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_sessions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='workouts.workoutsession')),
            ],
            options={
                'verbose_name': 'Session Participant',
                'verbose_name_plural': 'Session Participants',
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['status', 'scheduled_datetime'], name='workouts_wo_status_ae5d31_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['creator', 'status'], name='workouts_wo_creator_e39d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['participant', 'status'], name='workouts_wo_partici_f1f8ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionrequest',
            unique_together={('session', 'requester')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionparticipant',
            unique_together={('session', 'user')},
        ),
    ]
