# Generated by Django 5.2.16 on 2026-07-11 07:06

# pyrefly: ignore [missing-import]
import django.core.validators
# pyrefly: ignore [missing-import]
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin - Full control'), ('moderator', 'Moderator - Can manage members and sessions'), ('member', 'Member - Regular participant')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active Member'), ('inactive', 'Inactive - Left group'), ('banned', 'Banned')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, help_text='Application message')),
            ],
            options={
                'verbose_name': 'Group Membership',
                'verbose_name_plural': 'Group Memberships',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_datetime', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('max_attendees', models.IntegerField(default=20)),
                ('current_attendees', models.IntegerField(default=0)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_pattern', models.JSONField(blank=True, default=dict, help_text='Recurring pattern details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Group Session',
                'verbose_name_plural': 'Group Sessions',
                'ordering': ['scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='GroupSessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('going', 'Going'), ('maybe', 'Maybe'), ('not_going', 'Not Going'), ('attended', 'Attended'), ('no_show', 'No Show')], default='going', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session Attendance',
                'verbose_name_plural': 'Session Attendances',
                'ordering': ['session__scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Group name', max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True)),
                ('description', models.TextField(help_text='Group description and purpose', max_length=1000)),
                ('tagline', models.CharField(blank=True, help_text='Short catchy tagline', max_length=200)),
                ('group_type', models.CharField(choices=[('open', 'Open - Anyone can join'), ('closed', 'Closed - Requires approval'), ('private', 'Private - Invite only')], default='open', help_text='How people can join this group', max_length=20)),
                ('max_members', models.IntegerField(default=20, help_text='Maximum number of members', validators=[django.core.validators.MinValueValidator(2)])),
                ('focus_areas', models.JSONField(blank=True, default=list, help_text="Primary focus areas (e.g., ['strength', 'cardio', 'yoga'])")),
                ('workout_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('one_time', 'One-time Event')], default='weekly', help_text='How often the group meets', max_length=20)),
                ('primary_location', models.CharField(help_text='Primary meeting location', max_length=200)),
                ('meeting_days', models.JSONField(blank=True, default=list, help_text="Days of week the group meets (e.g., ['monday', 'wednesday'])")),
                ('typical_time', models.CharField(blank=True, help_text="Typical meeting time (e.g., '6:00 AM - 7:30 AM')", max_length=100)),
                ('fitness_level_required', models.CharField(blank=True, choices=[('any', 'All Levels'), ('beginner', 'Beginner Friendly'), ('intermediate', 'Intermediate+'), ('advanced', 'Advanced Only')], default='any', max_length=20)),
                ('equipment_needed', models.JSONField(blank=True, default=list, help_text='Equipment members should bring')),
                ('requirements', models.TextField(blank=True, help_text='Any requirements or expectations for members')),
                ('group_image', models.ImageField(blank=True, help_text='Group banner or logo', null=True, upload_to='groups/')),
                ('member_count', models.IntegerField(default=1)),
                ('session_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workout Group',
                'verbose_name_plural': 'Workout Groups',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
