# Generated by Django 5.2.16 on 2026-07-11 07:06

# pyrefly: ignore [missing-import]
import django.db.models.deletion
# pyrefly: ignore [missing-import]
from django.conf import settings
# pyrefly: ignore [missing-import]
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupsession',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_group_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupsessionattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='groups.groupsession'),
        ),
        migrations.AddField(
            model_name='groupsessionattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workoutgroup',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workoutgroup',
            name='moderators',
            field=models.ManyToManyField(related_name='moderated_groups', through='groups.GroupMembership', through_fields=('group', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupsession',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_sessions', to='groups.workoutgroup'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.workoutgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='groupsessionattendance',
            unique_together={('session', 'user')},
        ),
        migrations.AddIndex(
            model_name='workoutgroup',
            index=models.Index(fields=['slug'], name='groups_work_slug_966a1e_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutgroup',
            index=models.Index(fields=['group_type', 'is_active'], name='groups_work_group_t_521671_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutgroup',
            index=models.Index(fields=['-created_at'], name='groups_work_created_358021_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'status'], name='groups_grou_group_i_d0a4fa_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['user', 'status'], name='groups_grou_user_id_fbaf63_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('group', 'user')},
        ),
    ]
