# Generated by Django 5.2.16 on 2026-07-11 20:31

# pyrefly: ignore [missing-import]
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutgroup',
            name='primary_location',
            field=models.CharField(blank=True, help_text='Primary meeting location', max_length=200),
        ),
    ]
