# Generated by Django 5.2.16 on 2026-07-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_workoutgroup_primary_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutgroup',
            name='member_count',
            field=models.IntegerField(default=0),
        ),
    ]
