# Generated by Django 5.2.16 on 2026-07-11 07:06

# pyrefly: ignore [missing-import]
import django.db.models.deletion
# pyrefly: ignore [missing-import]
from django.conf import settings
# pyrefly: ignore [missing-import]
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        ('ratings', '0001_initial'),
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The group this rating is for (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='groups.workoutgroup'),
        ),
        migrations.AddField(
            model_name='rating',
            name='session',
            field=models.ForeignKey(blank=True, help_text='The workout session this rating is for (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='workouts.workoutsession'),
        ),
        migrations.AddField(
            model_name='rating',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['to_user', 'score'], name='ratings_rat_to_user_ea54c9_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['from_user', 'created_at'], name='ratings_rat_from_us_fbfa51_idx'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(condition=models.Q(('session__isnull', False)), fields=('from_user', 'to_user', 'session'), name='unique_rating_per_session'),
        ),
    ]
